
name: ResNet101
depth: 101
width: 64

# Architecture specifics:
stem: CIFAR

convolution: Standard
nonlin_fn: ReLU
normalization: BatchNorm2d

downsample: C  #  as in He et al., 2019
initialization: skip-residual
