
type: final
check_every_nth_step: ${hyp.steps}

measure_param_norm: True
measure_grad_norm: True
check_momentum: False


internal_batch_size_chunks: 1
record_gradient_norm_per_batch: False
compute_gradient_SNR: False
compute_gradient_noise_scale: False

compute_flatness: False
flatness_step_size: 0.1
flatness_threshold: 1.0
flatness_norm: filter

save_model_every_nth_step:
